#!/bin/bash

# Run autopep8 to check if formatting is ok
# (stdout suppressed, because it prints the whole diff)
echo "Checking python formatting..."
autopep8 --diff -r psASM/. ROMGeneration/. psPROG/Utility/. --max-line-length 160 --exit-code > /dev/null

if [ $? -eq 0 ]
then
    echo "autopep8: Python formatting OK!"
    exit 0
else
    echo "autopep8: Error! Pyhon not formatted. Run Utilities/format_all.sh!"  
    exit 1
fi


